baseURL = 'https://carvalhxlucas.pro/'
theme = "PaperMod"
defaultContentLanguage = 'en' # Default language

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

# --- Global settings ---
[params]
  author = { name = "Lucas Carvalho" }
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  # Social Icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/carvalhxlucas"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/carvalhxlucas"

# --- Settings: Portuguese (pt-br) ---
[languages.pt-br]
  languageName = "Português"
  weight = 1
  title = "Lucas Carvalho"
  
  # Portuguese bio
  [languages.pt-br.params.profileMode]
    enabled = true
    title = "Lucas Carvalho"
    subtitle = "AI/ML Engineer"
    imageUrl = "https://github.com/carvalhxlucas.png"
    imageWidth = 120
    imageHeight = 120
    [[languages.pt-br.params.profileMode.buttons]]
      name = "Meus Projetos"
      url = "/posts"
    [[languages.pt-br.params.profileMode.buttons]]
      name = "Sobre mim"
      url = "/sobre"

  # Portuguese menu
  [[languages.pt-br.menu.main]]
    identifier = "posts"
    name = "Projetos"
    url = "/posts"
    weight = 10
  [[languages.pt-br.menu.main]]
    identifier = "articles"
    name = "Artigos"
    url = "/articles"
    weight = 12
  [[languages.pt-br.menu.main]]
    identifier = "certifications"
    name = "Certificações"
    url = "/certifications"
    weight = 15
  [[languages.pt-br.menu.main]]
    identifier = "courses"
    name = "Cursos"
    url = "/courses"
    weight = 16
  [[languages.pt-br.menu.main]]
    identifier = "sobre"
    name = "Sobre"
    url = "/sobre"
    weight = 20

# --- Settings: English (en) ---
[languages.en]
  languageName = "English"
  weight = 2
  title = "Lucas Carvalho"

  # English bio
  [languages.en.params.profileMode]
    enabled = true
    title = "Lucas Carvalho"
    subtitle = "Software Engineer"
    imageUrl = "https://github.com/carvalhxlucas.png"
    imageWidth = 120
    imageHeight = 120
    [[languages.en.params.profileMode.buttons]]
      name = "My Projects"
      url = "/posts"
    [[languages.en.params.profileMode.buttons]]
      name = "About me"
      url = "/about"

  # English menu
  [[languages.en.menu.main]]
    identifier = "certifications"
    name = "Certifications"
    url = "/certifications"
    weight = 10
  [[languages.en.menu.main]]
    identifier = "courses"
    name = "Courses"
    url = "/courses"
    weight = 11
  [[languages.en.menu.main]]
    identifier = "posts"
    name = "Projects"
    url = "/posts"
    weight = 10
  [[languages.en.menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles"
    weight = 12
  [[languages.en.menu.main]]
    identifier = "sobre"
    name = "About"
    url = "/about" # Note que a URL muda
    weight = 20